ProofGeneral/PG

- generic/pg-assoc.el
- generic/pg-response.el
- generic/proof-shell.el
Hi,
Here is a patch trying to avoid deleting frames too eagerly when laying out windows for PG. In particular, if one opens a second frame and then restart scripting, the second frame is not deleted if it is displaying some other buffer.
Since this touches the generic code of pg, I let this pull request in order to let people comment. I will commit this pull request in a few days if nobody objects.
> Trying to not delete frames too eagerly when laying out.

- coq/coq.el
- generic/proof-shell.el
Hi Pierre,
Could you have a quick look at this? The bug that this attempts to fix is as follows:
In a clean coq buffer,
* Type and run "SearchAbout plus."
* Scroll to the bottom of the response buffer
* M-: (proof-shell-invisible-cmd-get-result "Check nat.")
The response buffer scrolls back to the top.
See https://github.com/cpitclaudel/company-coq/issues/8 and https://github.com/cpitclaudel/company-coq/issues/32 for some background info. Maybe we should not even call the delayed output hook? But that sounds like an invasive change.
> Fix spurious scrolling of *goals* and *response* buffers

- doc/Makefile.doc
Fixes a bug with producing HTML documentation under recent (less than 5 years
old) versions of texi2html.
texi2html, [as of version 1.80](http://download-mirror.savannah.gnu.org/releases//texi2html/NEWS-1.80),
uses -number-sections instead of -number for the flag name.
> Update numbering flag passed to texi2html

- .travis.yml
- Makefile.travis
This closes #27.  I found that no emacs before 24.3 builds on Travis.
> travis.yml for emacs 24.{3,4,5}

- doc/ProofGeneral.texi
Otherwise coq-load-path-safep fails. It seems to be nonrec everywhere else.
> coq-load-path docs: norec -> nonrec

- generic/pg-user.el
This a patch to fix #39
I have tested my branch only with GNU Emacs 24.3.1, so more testing is welcome.
Ref: https://github.com/ProofGeneral/PG/issues/39#issuecomment-230180627
Cc: @JasonGross @Matafou @cpitclaudel
> Fix (next-undo-elt) to return a relevant undo element w.r.t (undo-delta)

- COMPATIBILITY
- README.md
Starting with the latest version (10.12 "Sierra"), the operating system
is called macOS rather than Mac OS X.
Mac is technically the name of the hardware, not the operating system.
> Refer to Apple's operating system as macOS

- CHANGES
- coq/coq-abbrev.el
- coq/coq-compile-common.el
- coq/coq-par-compile.el
- coq/coq-par-test.el
- coq/coq-seq-compile.el
- coq/coq-system.el
- doc/ProofGeneral.texi
Select "Quick compilation mode" in the Coq menu. See also documentation of coq-compile-quick, the and-vio2vo stuff is not yet there.
This is a first version, there are several things to polish. I am especially not happy about the menu, I would like to have the quick compilation point in the settings menu, close to parallel compilation. However, the menu machinery behind defpacustom does not support radio menus. Other things to polish:
- ~~disable the quick menu for sequential compilation~~
- ~~8.4 compatibility~~
- ~~compilation warnings~~
- ~~update documentation~~
- ~~CHANGES file entry~~
> first version for quick compilation

- CHANGES
- coq/coq-abbrev.el
- coq/coq-compile-common.el
- coq/coq-par-compile.el
- doc/ProofGeneral.texi
- generic/proof-shell.el
With option coq-compile-keep-going set, parallel compilation continues after the first error to compile as much as possible and to potentially report more than one error.
Need to
- ~~write CHANGES~~
- ~~write doc~~
before merging.
@cpitclaudel if you have time I would be happy to receive your feedback!
> Keep going

- coq/coq.el
- generic/proof-config.el
- generic/proof-shell.el
This an attempt at fixing #154.
It seems to work, I would like to discuss the interaction with @hendriktews 's proof-tree, of which I mimick the way of inserting invisible commands in the action-list (nice by the way).
Hendrik, can you have a look please? I wonder if I should insert my commands before or after yours in proof-shell-exec-loop. Both are "Show." but mine is not no-response.
We could also merge both insertion in a single generic (proof-shell-invisible-commands-after-advancing-command). Or we may not bother since xml-pg has a different approach anyway.
> Fixing #154.

- .travis.yml
- Makefile.travis
Up to now the emacs-git Travis job was taking much more time w.r.t emacs24 (around 10min).
Now that emacs 25.1 and 25.2 has been released, I propose to build PG against them in place of emacs-git.
Hopefully this commit will shorten the real (elapsed) time of Travis CI automated build.
> [Travis CI] Replace emacs-git target with emacs-25.{1,2} stable targets.

- generic/proof-site.el
Without the string-end (`\\'`) it will match all file names which contain `.eca?`.
> Fix easycrypt automode regexp

- doc/ProofGeneral.texi
`make html` didn't work on my machine so I'm not sure how the html looks like, but the pdf generated by `make pdf` seems ok.
> Formatting fix for proof-layout-windows documentation

- coq/coq-response.el
- coq/coq-server.el
- coq/coq-span.el
- coq/coq-state-vars.el
- coq/coq-system.el
- coq/coq-tq.el
- coq/coq.el
There is an option, settable in `coq/coq-system.el`, to consider feedbacks with error message as failures, so they cause a retraction to the start of the span associated with the state id in the feedback.
Not well-tested, works on simple examples.
Fixes #232.
> Add option to consider error message feedbacks as failures (& Fix retract bugs)

- generic/proof-syntax.el
This breaks various other modes in recent Emacs, most noticeably git-region-history:
Error during redisplay: (jit-lock-function 1501) signaled (wrong-number-of-arguments #[(ad--addoit-function beg end loudly) "\306	\203 \0\307\310\311
!\312\313Q!!\203 \0\310\311
!\312\313Q!
#\210
#\211)\207" [ad-return-value proof-buffer-type proof-assistant-symbol beg end loudly nil fboundp intern symbol-name "-" "font-lock-fontify-syntactically-region" ad--addoit-function] 6] 3)
> Add a missing parameter in advice on font-lock-fontify-keywords-region

- coq/coq-system.el
This is similar to the builtins `compile-command`/`compilation-read-command`.
> Make coq-prog-args safe when list of strings.

- coq/coq-db.el
There is no `default-face` face, it should be `default`. I found this error when I `[M-x org-html-htmlize-generate-css]`.
> Fix coq-symbol-face's :inherit attribute

- coq/coq.el
This is pretty self explanatory; it's just another convenience function that I use pretty often and figure others might too. There's currently no default keybinding.
> Add coq-Print-Ltac to print an Ltac term

- coq/coq-smie.el
- coq/coq-syntax.el
- coq/coqtags
Syntactically looks much like an Inductive, though it is non-recursive
so "where" (mutual recursion) is not supported.
> Support the Variant vernacular

- generic/proof-script.el
With this change, the help context menu is accessible on either side of the hidden comment.
> extend helpspan, issue #158

- coq/coq-system.el
The result of parsing was in reverse, please see
https://github.com/ProofGeneral/PG/issues/392\#issuecomment-425227314
> Fix parsing of -arg in _CoqProject file

- coq/coq-system.el
When editing a remote file, the `coqtop` process will itself be remote, which means that the paths that are passed to it should be _local_, not remote. Otherwise, paths like `/ssh:hostname:/path/to/dir` get passed to `coqtop`, which has no idea what's going on.
I don't know elisp at all, so I'm not sure if there is a better way to write this, but it "seems to work" :) Also, I poked around at the TRAMP docs and couldn't find a more obvious way of doing this, though it seems like it should be a pretty common usecase (as anytime you want to pass arguments to something TRAMP has started, you want to do this renaming).
Also, this relates to (and should close) #203.
> Use non-remote path to expand paths in _CoqProject when file is remote.

- coq/coq-compile-common.el
There's this really annoying problem where if you take notes in org-mode and have Coq source blocks, proof general will prompt to save the fontification buffers when running Import statements in Coq.
https://lists.gnu.org/archive/html/emacs-orgmode/2016-03/msg00354.html
This is a simple fix to ignore these buffers,
> Ignore all ephemeral buffers and buffers not backed by a file

- generic/proof-utils.el
https://github.com/ProofGeneral/PG/issues/401
This seems to fix the problem! Previously mode-lines would disappear and it was really confusing for me.
> Remove code that hides mode-line.

- proof-general.el
This PR amounts to a trivial change (renaming), albeit necessary to simplify PG's setup using `use-package` as pointed out by @ejgallego in ProofGeneral/PG#398.
It also changes the `Commentary` text that will be displayed in http://www.melpa.org/#/proof-general (instead of `No description available.`)
FYI I have prepared a bootstrapped `.emacs` config in https://github.com/erikmd/tapfa-init.el for a course using Tuareg+Merlin+PG+company-coq starting on next Monday, and I'd like to simplify the `use-package` config of PG with this PR before the course starts.
So I plan to merge this on tomorrow Sunday Jan 13 at 12:00 +0100 or so, but if you have comments on the prose, feel free to comment! Cc @ProofGeneral/core
> Improve use-package support

- generic/proof-script.el
[prog-mode](https://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/progmodes/prog-mode.el?id=a18336a8dc754fa1c68e16dd8009466cf409271b) is the base mode for programming that comes with Emacs: “All major modes for programming languages should derive from this mode so that users can put generic customization on `prog-mode-hook`.”
> Derive proof-mode from prog-mode

- coq/coq-system.el
This makes it possible to run new and old coq versions consecutively
without manually cleaning coq-prog-args.
It's not the prettiest code but I don't know enough lisp to make it nicer.
> Clean -topfile for coq-prog-args properly

- CHANGES
- coq/coq-abbrev.el
- coq/coq-db.el
- coq/coq-diffs.el
- coq/coq.el
- doc/ProofGeneral.texi
- generic/pg-goals.el
- generic/pg-response.el
- generic/proof-config.el
- generic/proof-menu.el
- generic/proof-syntax.el
This PR highlights Coq proof diffs generated in goals and some error messages.  Showing these requires https://github.com/coq/coq/pull/10019.  This PR can be committed without waiting for that change--it will not break anything.  I hope that PR will be in Coq 8.10, which is scheduled for June.  
https://github.com/coq/coq/pull/10020 is needed to show the highlights when undoing proof steps--PG uses the "Show" command, which before this PR was not highlighting proof diffs at all.
Please see the doc in this PR and the Coq documentation at https://coq.inria.fr/distrib/current/refman/proof-engine/proof-handling.html#showing-differences-between-proof-steps.
Here are some screen shots.  The first shows additions only ("on" setting), the second shows the same proof step with the "removed" …
> Support Coq's proof diffs feature: highlight diffs in goals and some error messages

- coq/coq-diffs.el
- coq/coq.el
- generic/pg-goals.el
- generic/pg-response.el
Created a hook for coq-insert-tagged-text so that PG code can be loaded even if Coq support code is not loaded.
Updated that routine to process the changes in the buffer rather than from a string.
Updated comments
> Proof diffs revisions requested by @monnier

- coq/coqtags
As the pull request name
1. The coqtags program can't find some Theorem/Lemma of the following form
```coq
Lemma lemma_name arg1 arg2 : T1 -> T2
```
2. It can't extract the defintion name
```coq
Definition d := true.
``` 
coqtags will output
```
Definition d^?^A1,1
```
The correct one should be
```
Definition d^?d^A1,1
```
I try to fix these two problems.
Thank you for this excellent tool
> fix coqtags that can't find some theorem and output empty definition

- coq/coq-par-compile.el
Use coqc for vio2vo compilation instead of coqtop for Coq >= 8.10+alpha.
With https://github.com/coq/coq/pull/8690 vio2vo compilation (-schedule-vio2vo) was moved from coqtop to coqc, see also https://github.com/coq/coq/issues/10679. This commit makes PG compilation compatible with Coq after that PR. However, the patch only checks for the Coq version, therefore making PG vio2vo compilation fail on 8.10 versions before PR 8690. (Compilation still works, it's just that vio2vo postprocessing for the mode quick-and-vio2vo fails.)
> coq-par-compile: fix 8.10 -schedule-vio2vo incompatibility

- coq/coq-system.el
Currently, `-topfile` support of Coq PG doesn't work if `buffer-file-name` is `nil`, e.g., when proving in the `*scratch*` buffer. This PR changes it to do not use `-topfile` argument if `buffer-file-name` is `nil`.
> Make -topfile facility work for unnamed files

- coq/coq-syntax.el
This PR should fix #446 (tested with Emacs 25.1.1 on the MWE given by @JasonGross)
Cc @ProofGeneral/core can one of you approve the patch?
then we can merge it no later than on Monday.
Thanks again Jason for the report!
> Recognize "Timeout" before save keywords to fix #446

- CHANGES
- coq/coq-smie.el
- coq/ex/indent.v
- coq/ex/indent_monadic.v
- doc/ProofGeneral.texi
This a generalization of PR#451 proposed by @Chobbes.
Since these syntax are not completely universal (and not builtin in
coq), the idea is to make the syntax customizable, especially to make
it possible to disable it.
NOTE: to make the Compcert syntax supported I had to refine the smie
lexer so that the ";" token was emitted as a fllback instead of ";
tactic".
NOTE2: I had to make the coq-user-token and coq-monadic-tokens be
tested ON THE RESULT of smie-coq-backward-token.
> Generic monadic indentation + specifically ext-lib / Compcert + doc.

- generic/pg-autotest.el
- generic/pg-movie.el
- generic/proof-site.el
Patch proposed by @monnier to fix #464 .
> Fix 464: proof-autoloads not found by Emacs

- coq/coq-syntax.el
- Ltac2 definitions and types
- Ltac2 queries
- ltac1:(...) and ltac2:(...) antiquotations
There are definitely some things missing (eg, `Ltac Set`, `Ltac mutable foo := ...`, less common antiquotations), but this handles a bunch of common things.
Close #473
> Add support for core Ltac2 syntax

- CHANGES
- coq/coq-abbrev.el
- coq/coq-compile-common.el
- coq/coq-par-compile.el
- coq/coq-system.el
- doc/ProofGeneral.texi
This commit adds support for the new -vos compilation. For coq >=
8.11 only -vos can be used, depending on the config option
coq-compile-vos. For coq < 8.11 only -quick/-vio is used,
depending on option coq-compile-quick, as before. For a smooth
upgrade path, if coq-compile-vos has not been configured, the
users intention on whether to use -vos or not for coq >= 8.11 is
derived from coq-compile-quick.
Some defaults have been changed:
- parallel background compilation is the default now in case
coq-compile-before-require is enabled.
- for coq < 8.11, quick/vio compilation with delayed vio-to-vo
conversion is now the default
> coq-par-compile: support -vos for coq >= 8.11 and default setting change

- .github/workflows/test.yml
- doc/ProofGeneral.texi
Fixes the following error:
node `Coq Proof General' lacks menu item for `Proof using annotations' despite being its Up target
> doc/ProofGeneral.texi: fix makeinfo

- coq/coq.el
- doc/PG-adapting.texi
- easycrypt/easycrypt-hooks.el
- generic/proof-config.el
- generic/proof-script.el
- generic/proof-shell.el
- generic/proof-tree.el
proof-state-change-pre-hook happens earlier than
proof-state-change-hook, i.e. before proof-done-advancing. This should
be used to register information in the currently processed span before
proof-done-advancing classifies it.
Historically PG design was to gather these information during
proof-done-advancing (or in its hook called at the end) by just
looking at the command statement. But it is often useful to look at
the output (messages and/or prompt) to gather more accurate
information. Some of this information may be needed DURING
proof-done-advancing. Hence this early hook.
> New hook for early prompt/output analyzis.

- generic/proof-shell.el
Fixes a regression introduced in 22681a3caf2c8f45700585ea74dffbf48bb2ac19.
In particular, the Coq module seems to be the only one currently setting
`proof-show-proof-diffs-regexp`, causing an error for EasyCrypt.
> Use `proof-shell-string-match-safe` to avoid failing on `nil` regexp

- coq/coq-par-compile.el
The hash avoids an exponentially growing number of duplicates in
the ancestor collection. Fixes #499
> coq-par-compile: use hash for ancestors

- coq/coq.el
Fixing the auto insertion of `Proof using` in the case of a `with` annotation also present.
> Fix #518: "Proof using" mode corrupts "Proof with tac".

- coq/coq-indent.el
- coq/coq-smie.el
- coq/coq.el
- coq/ex/indent.v
It was hard to separate this 2 fixes (same regexps). Note in that in some cases pg still hangs, for instance `auto.{ }` makes it hang. I will try to make this better if I find some time. Not high priority though, we cannot deal with all possible ways of making a dynamic parser win against regexp.
Fixing windows issue with signals is beyond my ability. 
While at playing with regexp I implemented the support for named subgoals. Typical example of what is supported now:
```coq
Theorem lt_n_S : (True \/ True \/ True \/ True \/ True ) -> True.
Proof using Type with (auto).
refine (or_ind ?[aa] (or_ind ?[bb] (or_ind ?[cc] (or_ind ?[dd] ?[ee])))).
[aa]:{ intro. auto. }
2:{  intro... }
[ee]:{auto.}
[dd]:{  auto. }
auto.
Qed.
```
Command splitting and indentation seem OK.
Incidentally also fixed …
> Fix #514 + support for named goal selector.

- README.md
- ci/init-tests.el
* **Kind**: fix/test
* Close #529
* This patch fixes ProofGeneral's CI test suite (which was failing because of Emacs 26.1)
* See https://debbugs.gnu.org/cgi/bugreport.cgi?bug=34341 for details
* See also https://github.com/coq/coq/issues/12088#issuecomment-613522676
> Workaround & Document debbug 34341 (fixed in Emacs 26.3, 27.1)

- coq/coq-system.el
Use process-file and omit find-file-name-handler, because
process-file takes care of file handlers already.
Fixes #525
> fix coq-callcoq for emacs 27

- proof-general.el
load-file-name is not set to pg's source when compiling from doom-emacs
https://github.com/hlissner/doom-emacs/issues/2788
> Fix byte compilation

- coq/coq.el
Coq team is considering (https://github.com/coq/coq/pull/13656) changing all messages containing "subgoal[s]" into "goal[s]". This PR should makes PG compatible with this.
Making this change as early as possible so that as much users as possible have a compatible PG when this lands on coq master (if it does, since this change is still discussed).
> Nosub goals

- coq/coq-system.el
- doc/PG-adapting.texi
- doc/ProofGeneral.texi
- doc/docstring-magic.el
- generic/proof-config.el
- generic/proof-menu.el
- generic/proof-site.el
- generic/proof-unicode-tokens.el
- lib/texi-docstring-magic.el
`make -C doc magic`, the magical update of the documentation of variables and functions included in the manuals has been bitrotting since 2017 at least. This PR fixes several issues introduced in the PG sources and stemming from backward-incompatible changes of emacs. The last commit updates the manuals.
@erikmd : commit d675c2458a90c93552b86f1b975de5c2780c5fea here fixes the missing `@samp`'s that you observed in 6820af656d33bb87461c7dcfcb0d01813c8097cb.
> fix make magic and update manuals

- .github/workflows/test.yml
- ci/compile-tests/README.md
- ci/simple-tests/Makefile
- ci/simple-tests/README.md
- ci/simple-tests/test-coqtop-unavailable.el
- coq/coq-system.el
Uses of coq-callcoq need to correctly handle nil as result for
the case that coq-callcoq fails.
Additionally, add a regression test.
Fixes #551
> protect uses of coq-callcoq

- CHANGES
- generic/proof-autoloads.el
- generic/proof-menu.el
- generic/proof-utils.el
We sometimes have bug reports that amount to noticing that the version of PG that is installed is not fully up-to-date.
And even if the upgrade procedure is documented in https://proofgeneral.github.io/#keeping-proof-general-up-to-date (assuming a MELPA installation), I reckon it is not very straightforward to perform one such update.
Hence this PR that relies on package.el (and behaves in a safe way if the feature is not available thanks to `proof-try-require`).
To sum up, it is **merely** a shortcut for doing <kbd>M-x package-list-packages RET</kbd>, <kbd>r</kbd>, <kbd>U</kbd>, <kbd>x</kbd>, but forcing the use of a mini-buffer confirmation rather than a dialog-box for better UX, letting the end user to validate or not with `y/n`.
Below is one screenshot to give an overview of the …
> feat: Add proof-upgrade-menu triggering proof-upgrade-elpa-packages

- .github/workflows/test.yml
- README.md
- doc/ProofGeneral.texi
- proof-general-pkg.el
- proof-general.el
This small PR is a follow-up of the discussion I had with @hendriktews last month.
To sum up:
* Although it is nice to support many emacs versions, and periodically add more versions within the PG CI configuration,
it is also useful to drop support for very old emacsen at some point. Notably to be able to benefit from newest features :slightly_smiling_face:
* A possible policy that looked reasonable for @hendriktews and me is documented in the [`README.md` from this PR](https://github.com/ProofGeneral/PG/blob/3b93f2e1149ebd13e97d6fd4954269c07fe210bd/README.md#installing-proof-general).
The MELPA/package.el metadata will naturally be updated as well by this PR.
* **Summary:** support Emacsen from the versions packaged in **Debian Stable** and **Ubuntu LTS until EoS**; which implies to:
* …
> test: Add Emacs 27.1 in CI & Bump the minimal-required version of Emacs (24.5 for now)

- CHANGES
- coq/coq-abbrev.el
- coq/coq.el
Fix #563
Splitting the coq into two commands made me remove
coq-search-blacklist-string from defpgcustom. The visible effect is
that the menu entry has moved, and the command name changed. This is
explained in the CHANGES.
> Fix #563. Refactor search blacklist custom to avoid dual-send bug.

- coq/coq-smie.el
- coq/coq-syntax.el
Actually it seems that even multimatch and lazymatch was poorly supported.
Now `multimatch`, `lazymatch` and `multi_match` and `lazy_match` are recognized as `match` token. Note that the exclamation mark is ignored in `xxx_match!`.
> Fix #562. Lazy/multi_?match indentation support.

- CHANGES
- ci/simple-tests/.gitignore
- ci/simple-tests/omit_test.v
- ci/simple-tests/test-omit-proofs.el
- coq/coq-syntax.el
- coq/coq.el
- doc/PG-adapting.texi
- doc/ProofGeneral.texi
- generic/pg-user.el
- generic/proof-config.el
- generic/proof-faces.el
- generic/proof-menu.el
- generic/proof-script.el
- generic/proof-useropts.el
This commit adds a feature to recognize complete opaque proofs in
the asserted region and to replace them with an admitted proof.
This can drastically improve the processing time for the asserted
region at the cost of not checking the omitted proofs. Omitted
proofs are displayed in some shade of purple in the locked
region.
With this commit, the feature is supported for Coq for files in
which proofs are started with some form of Proof using and
ended with either Qed, Defined or Admitted.
To enable, configure proof-omit-proofs-option or click
Proof General -> Quick Options -> Processing -> Omit Proofs.
> add feature to omit complete opaque proofs

- CHANGES
- coq/coq-syntax.el
Close #581 
Demo screenshot:
<details><summary>Source code</summary>
```coq
Require Import ssreflect.
Goal True /\ True.
split.
{ exact: I. }
exact: I.
Qed.
Goal True /\ True.
split; [ exact: I | exact: I ].
Qed.
Check forall {T1 : Type} [T2 : Type], Type.
(* we just won't have some highlighting if ever we write *)
Check forall { T1 : Type } [ T2 : Type ], Type.
(* And there's no such highlighting with font-lock-variable-name-face in records
as it would be irrelevant for them, given projections are not variables *)
Require Import Floats.
Record cplx := { Re: float; Im: float }.
Check {| Re := 0%float ; Im := 0%float |}.
```
</details>
> Fix font-lock-variable-name-face when combining { or [ and ssreflect "colon tactics"

- doc/ProofGeneral.texi
Fix #596
I did a refresh on this part of the documentation.
I propose to merge this before adapting maybe according to #590.
> fix #596 - outdated documentation for setup coq-prog-xxx.

- coq/coq-system.el
Close #600 
Note: the function `(coq--version<)` already supported `_+rcN` suffixes.
So the compatibility issue was just coming from the fact `coqtop -v`
changed its output format; namely:
The Coq Proof Assistant, version 8.13.2 (September 2021)
compiled on Sep 12 2021 11:24:20 with OCaml 4.07.1
The Coq Proof Assistant, version 8.14+rc1
compiled with OCaml 4.12.0
> fix: parsing of `coqtop -v` for 8.14+rc1

- coq/coq-syntax.el
- coq/coq.el
The regexp change in 8215623 to support "Fail" command had to be
refined to capture correctly some error messages.
> Fix #614. Cause by 8215623.

- ci/test-indent/indent-tac.v
- coq/coq-indent.el
- coq/coq-smie.el
Had to change the associativity from `left` to `assoc` for token
`"."`. This speeds up things by limiting smie token lookups.
I had to change a few indentation rules to restore the correct
behaviour with the new grammar. I had to:
- use `smie-indent-virtual`
And as side effects:
- fix a wrong tests.
- fix bugs in find-real-start with sequences of "{ subproof" and comments.
Left for another PR: cleaning up dead code in coq-indent.el.
> Fix #625 Indentation very slow.

- coq/coq-system.el
Reported by a student of @al3623
```
File mode specification error: (coq-unclassifiable-version . 8.15.0^M
compiled)
```
The workaround if the student can't update after this PR is merged would be `(setq coq-pinned-version "8.15.0")`
> Fix version number parsing on some confused Windows installations

- coq/coq-smie.el
- coq/coq-syntax.el
Indentation + syntax highlighting.
> Fix #618 - Support for command "Derive SuchThat As".

- CHANGES
- ci/test-indent/indent-equations.v
- ci/test-indent/indent-inside-command-boxed.v
- ci/test-indent/indent-inside-command.v
- ci/test-indent/indent-tac.v
- coq/coq-mode.el
- coq/coq-smie.el
Fix #646.  Now indentation of function arguments are indented wrt to the function instead of aligned with the first argument. See details below.
- Is it too late for the including this in the soon to come V.4.5 tag? The indentation CI test are a good clue that this does not break indentation too much but we may wait for users to test this a bit.
- should we make the old behaviour still possible with a switch? I don't thinks `coq-indent-box-style` would be the right switch. I am not found of addig one more switch.
This patch indents like this:
```
Definition foo :=
myfunction (args1) arg2
arg3.
```
instead of 
```
Definition foo :=
myfunction (args1) arg2
arg3.
```
Besides when a function application is placed immediately after (and on the same line as) a "Com start" token, indentation is …
> Fix #646. Indentation of function arguments.

- generic/proof-shell.el
- generic/proof-useropts.el
I can't be the only one that is bothered by this! Every time you switch between files proof general kills and restarts the goal and response buffers. This is particularly painful if you have `proof-multiple-frames-enable` set --- I want to let xmonad handle the windows instead of emacs, but then every time I edit a new file the frames are deleted and new ones are created, messing up the layout. This PR adds a custom variable to disable this behaviour.
Happy to make changes if necessary!
> Add an option to stop proof-shell-kill-function from killing buffers.

- .github/workflows/test.yml
- ci/test_wholefile.v
Testing if replacing lia with omega in test suite is OK for all old versions. then that would fix the coq-8.15 test failure (deprecated omega was removed in coq-8.15).
> test: Replace `omega` with `lia` in CI & Add Coq versions

- coq/coq-system.el
A haphazard sketch to issue #589. It is *not* an acceptable final solution, I think
coq_makefile parses _CoqProject files in a slightly weird way. If we write `-arg "a b"` in _CoqProject then it passes the arguments `a` and `b` to coqc, but if we write `-arg "'a b'"` it passes `a b` to coqc, as a single argument.
I tried to adapt PG to this behavior. It works for my use-case, but I haven’t tested where the differences in behaviour (between PG and coq_makefile) lie now. A weird fact is, that coq_makefile produces some string, which it stores in `Makefile.coq.conf`, which later gets processed by make and passed on to coqc. So a "good" solution would try to reproduce the complete processing chain, i.e. first the processing done by coq_makefile, then the processing done by make.
Maybe we …
> Handle single-quotes in arguments to `-arg`

- coq/coq-smie.el
- coq/coq.el
- generic/proof-shell.el
All the emacs 25 tests failed in PR #626 because of these functions after I rebased that PR to current master.
> emacs 25 compatibility: don't use caddr or cadddr

- generic/proof-script.el
This restores the default behaviour of Emacs. If a user wants to be more
careful about saving temporary buffers, they can set `buffer-offer-save` via
the appropriate hooks.
This commit effectively reverts b8cca128a40ee0d72bc627a5d320cdde12b3d87c
Closes #668
> Do not offer to save (temporary) buffers without associated files

- generic/proof-unicode-tokens.el
When running proof-unicode-tokens-toggle on proof-general-20221130.946, the following error was printed to *Messages*.
```
proof-unicode-tokens-configure: Invalid function: proof-ass-symv
```
This may be because proof-unicode-token.el does not load macros, so I applied this patch.
> Invalid function error on proof-unicode-tokens-toggle

- doc/ProofGeneral.texi
- generic/pg-user.el
> feat: Make `C-c C-RET` and `C-c C-b` see prefix argument as a real toggle

- ci/simple-tests/omit_test.v
- ci/simple-tests/test-omit-proofs.el
- coq/coq-system.el
Test omit-proofs-never-omit-hints uses a feature ('#[local]') that has only been introduced in Coq 8.9. If we continue our current support policy, we will stop to support Coq 8.10 and older in April 2023. Instead of a proper fix, I therefore decided to simply skip the test for Coq 8.8 or older.
> test-omit-proofs: skip for Coq 8.8 or older

- ci/coq-tests.el
- coq/coq-system.el
> ci/coq-tests: expect 060_coq-test-wholefile to fail for 8.17

- generic/proof-site.el
> ⛔ Warning (comp): proof-site.el:249:2: Warning: defvar `proof-general-configured-provers' docstring wider than 80 characters
> [minor] silence an Emacs warning about above-80-chars docstring

- coq/coq-system.el
Fixes #707.
The first commit is purely the bugfix. (Note: I didn't understand the previous code, as I am no Elisp expert, maybe it is doing something really important besides producing very obscure failure modes?)
The second commit turns `warn` into `message`. When testing with only the first commit I did not manage to see the `warn` string anywhere on my Emacs, so the error is a bit too silent to my taste. (We are noticing that the user _CoqProject is broken and just silently ignoring it.) `message` is slightly better. I wonder if `error` wouldn't be even better, but the current code logic is to be resilient and ignore the error, so I kept that.
> Fix "Bad bounding indices" error on invalid _CoqProject

- CHANGES
- ci/compile-tests/010-coqdep-errors/Makefile
- ci/compile-tests/010-coqdep-errors/a.v
- ci/compile-tests/010-coqdep-errors/b.v
- ci/compile-tests/010-coqdep-errors/c.v
- ci/compile-tests/010-coqdep-errors/d.v
- ci/compile-tests/010-coqdep-errors/e.v
- ci/compile-tests/010-coqdep-errors/runtest.el
- ci/compile-tests/README.md
- coq/coq-compile-common.el
- coq/coq-par-compile.el
- coq/coq-system.el
Add 3 tests to check that coqdep errors are reliably detected, see also issue #722. Two of them are expected to fail for 8.19, because coqdep output changed in that version.
> reliably detect coqdep errors for 8.19

- doc/PG-adapting.texi
- doc/ProofGeneral.texi
In most cases, this is a simple replacement, using @pxref in most cases.
Closes #721
> texinfo manuals: fix obsolete @inforef

- coq/coq-mode.el
The current definition of 'coq--parent-mode is as follows:
```elisp
(defun coq--parent-mode ()
(if coq-use-pg (proof-mode) (prog-mode)))
```
It currently functions correctly. However, this definition breaks the major mode hierarchy. For example:
```elisp
(get 'coq-mode 'derived-mode-parent)
; => 'coq--parent-mode
``` 
And the built-in Emacs function, `derived-mode-p`, also cannot recognize that `coq-mode` is a sub-mode of `prog-mode`:
```elisp
;; when you are in coq buffer
(derived-mode-p 'prog-mode)
; => nil
```
Some Emacs code, such as Spacemacs, relies on this information to determine if a buffer is a text/program file. For example, Spacemacs will display line numbers for all sub-modes of `prog-mode` and `text-mode` when `dotspacemacs-line-numbers` is set to `t` (See the …
> coq/coq-mode.el: Change the definition of 'coq--parent-mode

- ci/simple-tests/omit_test.v
8.19 does not tolerate Proof using after let. Until now this problem was hidden by the two expected fails.
> simple-tests/omit_test: fix Coq sources for 8.19

- coq/coq-compile-common.el
- coq/coq-par-compile.el
User options coq-compile-extra-coqc-arguments and
coq-compile-extra-coqdep-arguments are added as list of arguments to invocation of, respetively, coqc and coqdep in addition to the arguments computed, e.g., from _CoqProject.
This can be used to work around #724.
> coq-par-compile: add user options for extra coqc/coqdep arguments

- ci/simple-tests/README.md
- ci/simple-tests/test-goals-present.el
Most of these tests currently fail because of different instances
of #568, see also #429, #467.
> add tests for checking that goals are correctly shown

- ci/coq-tests.el
The purpose of unwind-protect is to execute the cleanup-forms in case of a non-local exit. It does not make any sense to move these forms behind unwind-protect.
> coq-tests: fix error introduced by Cyril Anaclet in 0ae25c5a

- .github/workflows/test.yml
For whatever reason, the test job always runs late in a CI run (I am blaming the max-parallel annotation for this). This leads to longer CI runs, because, at the end, for several rounds on 6 instances of the test job are executing. Note that Github starts at most 20 of our tests in parallel, so it is not our responsibility to ensure that limit.
> CI: do not artificially restrict parallel test execution

- lib/texi-docstring-magic.el
This reverts commit a63a9b13185b0a2f13eb417165708f9cf38cc827 because it breaks CI.
> Revert "(texi-docstring-magic-texi-for): Use `help-function-arglist`"

- ci/simple-tests/README.md
- ci/simple-tests/coq-test-three-window.el
- doc/ProofGeneral.texi
- generic/pg-response.el
- generic/proof-useropts.el
These tests are for #760 and some of them fail because of this problem.
> fix 3-pane mode for small frame heights

- CHANGES
- ci/simple-tests/Makefile
- ci/simple-tests/README.md
- ci/simple-tests/coq-test-omit-proofs.el
- ci/simple-tests/coq-test-proof-stat.el
- ci/simple-tests/proof_stat.exp-out
- ci/simple-tests/proof_stat.v
- coq/coq.el
- doc/PG-adapting.texi
- doc/ProofGeneral.texi
- generic/pg-user.el
- generic/proof-config.el
- generic/proof-menu.el
- generic/proof-script.el
Work towards a feature that permits to extract lists of failing proofs from PG. Similar to what coq/coq#11479 would provide.
> poor PG man's workaround for coq/coq#11479

- generic/proof-splash.el
The idea is that this splash screen annoys everyone, even in its new manga-style form.
I would even consider removing it completely but at least let us not have it last for 8 seconds by default.
> Reduce splash time to 1s.

- ci/simple-tests/coq-test-omit-proofs.el
- ci/simple-tests/coq-test-proof-stat.el
- ci/simple-tests/omit_test.v
- ci/simple-tests/proof_stat.human.exp-out
- ci/simple-tests/proof_stat.tap.exp-out
- ci/simple-tests/proof_stat.v
- coq/coq-syntax.el
- coq/coq.el
- doc/PG-adapting.texi
- doc/ProofGeneral.texi
- generic/pg-user.el
- generic/proof-config.el
Currently bullets and braces are classified as commands that prevent proof omission, which is wrong.
> also omit proofs with bullets and braces

- coq/coq.el
Related: https://github.com/ProofGeneral/PG/issues/773
@hendriktews do you agree that we merge this ? (if the CI passes, of course)
> fix(coq.el): (setq proof-shell-strip-crs-from-input nil)

- ci/coq-tests.el
- coq/coq-syntax.el
- coq/coq.el
- generic/proof-config.el
- generic/proof-shell.el
As suggested by @hendriktews: added a "no-error" regexp.
Also adapted the tests so that they pass with coq pre-8.20 and post-8.20. No need to ass more tests case imho.
> Fixes #779 regression cannot step Fail correctly.

- ci/coq-tests.el
- ci/test_error_loc_1.v
- coq/coq.el
We cannot use the " ^^^ " thing to compute the error location because commands are not stripped of newlines anymore (#774).
Solution: use the character position information with the following subtleties
- position are given by coq as **bytes** positions.
- position given by coq is the position from the previous "." fed to coq. I.e. we must be careful to strip any blank after the final "." ofthe previous (hence from all) commands.
> Fix #781 PG does not position to error.

- coq/coq-indent.el
- coq/coq-system.el
According to the code of coq_makefile, ~`\r` is not considered white-space in _CoqProject. But `\t` is.~ `\t` is considered white-space.
Source: https://github.com/coq/coq/blob/a7f51315db5d70888af3b96a579eb799a2b45ca9/lib/coqProject_file.ml#L84
The second commit of this PR removes a duplicate function definition.
> Change _CoqProject separator settings

- ci/compile-tests/011-current-buffer/Makefile
- ci/compile-tests/011-current-buffer/a.v
- ci/compile-tests/011-current-buffer/b.v
- ci/compile-tests/011-current-buffer/c.v
- ci/compile-tests/011-current-buffer/d.v
- ci/compile-tests/011-current-buffer/runtest.el
- ci/compile-tests/README.md
- ci/compile-tests/bin/coq-error
- ci/compile-tests/cct-lib.el
- coq/coq-par-compile.el
- coq/coq-system.el
> test that Coq background compilation is not affected by local variables

- coq/coq-par-compile.el
- generic/proof-shell.el
... for the argument lists of background processes started by PG
> coq/generic: display empty strings in diagnostic messages

- ci/coq-tests.el
- ci/test_error_loc_fst_cmd.v
- coq/coq-indent.el
Small annoying bug seemingly squashed.
I think this solves #814 and the fact that the error was not correctly located.
> Fix problems with error on the first command of a file.

- ci/test-indent/indent-tac.v
- coq/coq-indent.el
- coq/coq.el
A small bug in the code for finding the real start of a command. It was wrong in the case of focus commands `3:{`.
The side effects of this should be almost invisible. I detected the bug when debugging experimental stuff.
> Fix low level code to find the start of a command.

- Makefile
Forwarding [Gentoo Linux bug 950240](https://bugs.gentoo.org/950240).
Gentoo is replacing the `which` command in Makefiles and other build scripts, because it is not portable, and its existence isn't guaranteed by POSIX.
Debian does the same since some time, see https://lwn.net/Articles/874049/ for an elaborate rationale.
This PR replaces `which` by `command -v` which is mandated by POSIX.
> Makefile: Replace "which" by POSIX "command -v"

- coq/coq-db.el
coq/coq-db.el:31:11: Warning: defconst ‘coq-syntax-db’ docstring has wrong usage of unescaped single quotes
fixed
> #795, Compiler warnings: wrong usage of unescaped single quotes

- ci/test-indent/indent-backslash-ops.v
- coq/coq-smie.el
The lexer now glues a "\" to an immediately following word if it is itself preceded by a space.
Note that for really good indentation you should try to add something like this to your configuration:
(setq coq-smie-user-tokens '(("\\in" . "=")))
to tell the indentation grammar that \in has the same precedence as "=".
> Fix #757 indentation of "\in"

- generic/proof-script.el
As per `proof-ignore-for-undo-count`'s [declared type](https://github.com/ProofGeneral/PG/blob/bbbb1e2604996513cd05f54da1b8ef059a8e8968/generic/proof-config.el#L484-L490), it is possible for it to be a function.
This is a simple commit that fixes an error when you try using it as such.
> Fixed an error when `proof-ignore-for-undo-count` is a function.

- doc/PG-adapting.texi
- lib/texi-docstring-magic.el
Pick two commits from Stefan from March 2024 that fix `make magic` for 30.1 and also improve it. I reverted these commits back then in a race and misunderstanding in order to regain an error-free CI baseline on master.
> Fix make magic

- CHANGES
- generic/proof-shell.el
This PR is only about the commit in the title. To avoid conflicts, it builds on PR #791.
I have disabled this silly question about killing Coq when quitting Emacs decades ago already. IMO we don't need a user option to control this behavior.
> proof-shell: Don't ask about killing the proof assistant on exit

- CHANGES
Fix commit 1f9484f50e1df85552464c815fbe6c166e3efefb by removing the CHANGES note that belongs to PR #791.
> CHANGES: remove wrongly merged note

- CHANGES
- doc/ProofGeneral.texi
- generic/proof-menu.el
- generic/proof-splash.el
- generic/proof-useropts.el
- add menu entry to disable splash screen to quick options
- add info to the splash screen on how to leave and disable the splash screen
- add Proof-General menu to splash screen, such that the hints on the splash screen make sense
- fix saving of quick options for several options
- the CHANGES entry also describes commit ea0f007c
- adapt manual
> improve hints on splash; fix quick options saving

- ci/simple-tests/README.md
- ci/simple-tests/coq-test-goals-present.el
When running silent, the error about a missing section variable is not always shown correctly.
> CI: add new tests for error messages at Qed

- ci/simple-tests/coq-test-goals-present.el
- coq/coq.el
- doc/PG-adapting.texi
- generic/proof-shell.el
Before this change, proof-shell-delayed-output-{start,end,flags} were only set inside proof-shell-filter-manage-output but never reset. Setting these variables happens immediately before the call to proof-shell-exec-loop, i.e., after processing urgent messages in proof-shell-process-urgent-messages and after handling errors in proof-shell-handle-immediate-output. Therefore urgent and error messages were processed with stale values in
proof-shell-delayed-output-{start,end,flags} that corresponded to the previous piece of processed output. This resulted at least in the following odd behavior:
- On error, the previous output was processed again with proof-shell-handle-delayed-output and the error was often classified as goals in proof-shell-last-output-kind.
- On error, both …
> generic: reset proof-shell-delayed-output-{start,end,flags} regularly
