ProofGeneral/PG

coq/coq-par-compile.el
coq/coq-seq-compile.el
coq/coq-system.el

Hey Pierre,
I've taken a stab at fixing #21. Does this look good to you?
Looking at the docs of coq_makefile, it seems it never supported -Q or -R with one option, so I dropped support for that. This makes the code much simpler.
Cheers,
Clément.

Refactor the project file parsing code

---

coq/coq.el

Fixes to get basic proof tree functionality, including support for
give_up, cycle, swap, revgoals. Unshelve and evar's don't work yet, see
proof-tree issues #1 and #2

basic proof tree changes for Coq 8.5

---

coq/coq.el

Fixes #67.
@Matafou Ok to merge?

Respect user settings in coq-insert-intros

---

coq/coq-syntax.el

Highlight Existing Class like Existing Instance

---

generic/pg-response.el
lib/span.el

Fixes #97 and (probably) #8. Thanks @cpitclaudel!

Ensure PG overlays have pg-span property

---

coq/coq-compile-common.el
coq/coq-par-compile.el
coq/coq-system.el

This is hopefully an improvement over PR #6

die gracefully when visiting files in nonexisting directories

---

coq/coq-syntax.el

I couldn't figure out whether or not to put a final `.`; I left it off as in `Axiom`

Add {Local ,}Axioms like {Local ,}Axiom, fix Parameters

---

coq/coq-indent.el

The change here seems to fix the problem, but it should be reviewed.
Fixes #223.

Look for vernac controls before focus bracket, possible fix for #223

---

CHANGES
generic/proof-menu.el

Close ProofGeneral/PG#31
Tested in both GUI and TTY PG (with company-coq)
Can be squashed-and-merged

Bind C-c C-m (= C-c RET) to proof-goto-point [tty]

---

README.md

Hi @cpitclaudel @Matafou 
I'm opening this PR to follow-up our latest e-mail discussion.
If the phrasing is OK for you, I can merge this tomorrow (in master + async modulo the merge conflict).

Update README.md (about PG branches and license)

---

README.md

**Kind:** documentation
Close #222

README.md: Update installation instructions for MELPA

---

generic/pg-goals.el

Remove stray h

---

coq/coq.el

I know nothing about elisp, and I did not test it... please don't laugh ;-)
Fix #433

Backtrack -> BackTo

---

doc/ProofGeneral.texi

Fix documentation about Coq electric terminator

---

coq/coq.el

feat(coq-insert-intros): Conditionally insert `move=>` or `intros`

---

coq/coq-par-test.el
etc/testsuite/pg-pgip-test.el
etc/testsuite/pg-test.el

this PR is a follow-up of https://github.com/ProofGeneral/PG/issues/493#issuecomment-634493988

fix: test files should not provide features

---

coq/coq-par-compile.el

make-temp-file without text argument for emacs 25

---

doc/PG-adapting.texi
generic/proof-shell.el

@Matafou @erikmd this is the priority action item feature we talked about yesterday

add proof-priority-action-list

---

ci/compile-tests/007-slow-require/Makefile
ci/compile-tests/007-slow-require/b1.v.orig
ci/compile-tests/007-slow-require/b3.v.orig
ci/compile-tests/007-slow-require/b4.v.orig
ci/compile-tests/007-slow-require/b5.v.orig
ci/compile-tests/007-slow-require/b6.v.orig
ci/compile-tests/007-slow-require/runtest.el
ci/compile-tests/008-default-dir/Makefile
ci/compile-tests/008-default-dir/a.v.orig
ci/compile-tests/008-default-dir/b.v.orig
ci/compile-tests/008-default-dir/c.v.orig
ci/compile-tests/008-default-dir/runtest.el
ci/compile-tests/README.md
ci/compile-tests/bin/compile-test-start-delayed
ci/compile-tests/bin/coqc-delayed
ci/compile-tests/bin/coqdep-delayed
ci/compile-tests/cct-lib.el
coq/coq-par-compile.el

These issues with default-directory became really apparent when working on tramp. However, they are not trump specific, a quick user can also trigger them without tramp.

fix several default-directory issues

---

.github/workflows/test.yml
CHANGES
COMPATIBILITY
README.md
coq/coq.el
doc/ProofGeneral.texi
proof-general-pkg.el
proof-general.el

* Require Emacs 25.1
* Update CI config accordingly (also adding Coq 8.12, 8.13)
* & Remove duplicate form mentioned by @Ptival in #504

Require Emacs 25.1 & Update CI config

---

.github/workflows/test.yml
.gitignore
Makefile
ci/coq-tests.el

* ci/coq-tests.el (070_coq-test-regression-wholefile-no-proof):
Clarify the intention of the test.
* Makefile (check): Fix comment.
(tests): New target.
* .gitignore: Add `ci/.lia.cache`, apparently generated by ci/test.sh

Minor tweaks encountered while trying to run the CI tests

---

proof-general.el

* Close ProofGeneral/PG#641
* Cc @dominique-unruh: let me know if the wording of this patch looks good to you or not

docs: Change MELPA doc

---

coq/coq-smie.el
coq/coq-syntax.el
coq/coq.el

Bug pointed in #51 (not the subject of the bug report though).

Fix indent user prefs

---

ci/coq-tests.el
ci/test_proof_using.v
coq/coq.el

Also added a test. Not sure which versions of coq support this. Let us see with CI.

Fix #599, bad detection of "Proof" in "Proof using" suggestions.

---

CHANGES

Ping @dominique-unruh for approval and references.

Adding QRHL-tool in the CHANGES file.

---

README.md

As mentioned [here](https://github.com/ProofGeneral/PG/commit/e06a7704a53ee43c4695681c0e40edfdf9b1124d#commitcomment-78639609).  I hope the order is OK.

Mention NonGNU ELPA

---

README.md

[*Current README.md*](https://github.com/ProofGeneral/PG#readme)
[Direct link to the PR's rendered README.md](https://github.com/ProofGeneral/PG/blob/7e27daf51c391cafca3fd9a1aafc407de218acdb/README.md)

docs(README.md): Update badges

---

coq/coq-syntax.el

This is a valid tactic. You can find it in the [manual](https://coq.inria.fr/distrib/current/refman/proofs/writing-proofs/equality.html#coq:tacn.native_compute).

Add Coq tactic "native_compute".

---

coq/coq.el

I believe this change is unproblematic, if nobody objects I will merge at the end of the coming week.

coq/coq.el: add a tiny bit of documentation

---

.github/workflows/test.yml
ci/coq-tests.el
coq/coq-system.el

Change to the CI strategy that has been agreed with @Matafou and @erikmd.

New testing

---

doc/PG-adapting.texi
lib/texi-docstring-magic.el

This reverts commit f620526756c6f24ddf40c515c6cc9bba969a6535 which was pushed directly without running CI.

Revert "texi-docstring-magic.el: Fix regression in last change"
